// Generated by CoffeeScript 1.9.1
'use strict';
$('#fullpage').fullpage({
  scrollOverflow: true,
  anchors: ['section1', 'section2', 'section3', 'section4'],
  menu: '#menu',
  css3: true,
  continuousVertical: false,
  resize: false
});
